# Generated by Django 6.1 on 2026-08-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.URLField(blank=True)),
                ('banner', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('sales_count', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('join_date', models.CharField(blank=True, max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('response_rate', models.CharField(blank=True, max_length=20)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
