# Generated by Django 6.0.7 on 2026-08-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='sales_count',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
